language: node_js

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - export PATH=$HOME/.yarn/bin:$PATH

cache:
  yarn: true

branches:
  only:
   - master
   - develop

script:
  - yarn run coverage
  - yarn run lint

after_success:
  - yarn run coverage-report
